language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: F5HhplrMsfaBp1SOMqED8U7N/0bnghrTh9gprtuGsF1Evrpcswifhye8ufy4OWLM2yhSFx05i82KO2xmxtc9hQ1TVcdiEq5yqheCl8VjopQjIUALasvbot3M7B76ks5TJvorEx0xfHugY8iE8Q58TKOGZ+ksz4tmVM603F2vTz8=
  - secure: AIPBHzA0q9LYHgjY5JysiTn1AY5ps3z6o+jy3ihsYO3PlaR4FmpbwdmtYKiopaRqSDOyO2KXCGc9uDVYu5j4/BC4INr0PG2crdqe+YlZdBgUOhKEQ489yEkg981uI9dSTCY/beefg7+xKWR64unoNyP9tHjpbDPKS6y4uGDQGVA=
  - secure: HChlgfRw6geSB1c80aaHS3sx0490voZu2Gg7Y7yylUEMRdPgyZ6a6xuIPAGuwHbXI+4N+h4/xKIK5+LyDzFXQYZeSH2Clw3shqc5vJk/aDRELPjkYaMYso73Fq/oHTy72Z2hWOup05BIBzmq5gPmvycgJ1nRCttQtTuvztfF7N8=
